repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --check ./
        description: "Python formatter"
        language: system
        types: [python]
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: flake8 --ignore=E501 ./
        description: "Linter"
        language: system
        types: [python]
        pass_filenames: false
      - id: isort
        name: isort
        entry: isort --check-only ./
        language: system
        types: [python]
        pass_filenames: false